config/routes.rb
Artwareclients20::Application.routes.draw do
  resources :artworks

  resources :exhibitions

  root :to => 'visitors#new'
end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  has_and_belongs_to_many :exhibitions
end

app/models/exhibition.rb
class Exhibition < ActiveRecord::Base
    has_and_belongs_to_many :artworks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: [:show, :edit, :update, :destroy]

  # GET /artworks
  # GET /artworks.json
  def index
    @artworks = Artwork.all
  end

  # GET /artworks/1
  # GET /artworks/1.json
  def show
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks
  # POST /artworks.json
  def create
    @artwork = Artwork.new(artwork_params)

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to @artwork, notice: 'Artwork was successfully created.' }
        format.json { render action: 'show', status: :created, location: @artwork }
      else
        format.html { render action: 'new' }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artworks/1
  # PATCH/PUT /artworks/1.json
  def update
    respond_to do |format|
      if @artwork.update(artwork_params)
        format.html { redirect_to @artwork, notice: 'Artwork was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @artwork }
      else
        format.html { render action: 'edit' }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1
  # DELETE /artworks/1.json
  def destroy
    @artwork.destroy
    respond_to do |format|
      format.html { redirect_to artworks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artwork
      @artwork = Artwork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artwork_params
      params.require(:artwork).permit(:title, :year, :description, :medium, :dimensions)
    end
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
  before_action :set_exhibition, only: [:show, :edit, :update, :destroy]

  # GET /exhibitions
  # GET /exhibitions.json
  def index
    @exhibitions = Exhibition.all
  end

  # GET /exhibitions/1
  # GET /exhibitions/1.json
  def show
  end

  # GET /exhibitions/new
  def new
    @exhibition = Exhibition.new
  end

  # GET /exhibitions/1/edit
  def edit
  end

  # POST /exhibitions
  # POST /exhibitions.json
  def create
    @exhibition = Exhibition.new(exhibition_params)

    respond_to do |format|
      if @exhibition.save
        format.html { redirect_to @exhibition, notice: 'Exhibition was successfully created.' }
        format.json { render action: 'show', status: :created, location: @exhibition }
      else
        format.html { render action: 'new' }
        format.json { render json: @exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exhibitions/1
  # PATCH/PUT /exhibitions/1.json
  def update
    respond_to do |format|
      if @exhibition.update(exhibition_params)
        format.html { redirect_to @exhibition, notice: 'Exhibition was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @exhibition }
      else
        format.html { render action: 'edit' }
        format.json { render json: @exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibitions/1
  # DELETE /exhibitions/1.json
  def destroy
    @exhibition.destroy
    respond_to do |format|
      format.html { redirect_to exhibitions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exhibition
      @exhibition = Exhibition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exhibition_params
      params.require(:exhibition).permit(:title, :site, :city, :opening, :closing, :comment)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/views/artworks/_form.html.erb
<%= form_for(@artwork) do |f| %>
  <% if @artwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
      <% @artwork.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :medium %><br>
    <%= f.text_field :medium %>
  </div>
  <div class="field">
    <%= f.label :dimensions %><br>
    <%= f.text_field :dimensions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artworks/edit.html.erb
<h1>Editing artwork</h1>

<%= render 'form' %>

<%= link_to 'Show', @artwork %> |
<%= link_to 'Back', artworks_path %>

app/views/artworks/index.html.erb
<h1>Listing artworks</h1>

<table  class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Year</th>
      <th>Medium</th>
      <th>Dimensions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artworks.each do |artwork| %>
      <tr>
        <td><%= artwork.title %></td>
        <td><%= artwork.year %></td>
        <td><%= artwork.medium %></td>
        <td><%= artwork.dimensions %></td>
        <td><%= link_to '', artwork, :class => 'glyphicon glyphicon-picture' %></td>
        <td><%= link_to '', edit_artwork_path(artwork), :class => 'glyphicon glyphicon-pencil' %></td>
        <td><%= link_to '', artwork, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'glyphicon glyphicon-trash'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artwork', new_artwork_path, :class => 'btn btn-primary'  %>

app/views/artworks/new.html.erb
<h1>New artwork</h1>

<%= render 'form' %>

<%= link_to 'Back', artworks_path %>

app/views/artworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @artwork.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @artwork.year %>
</p>

<p>
  <strong>Description:</strong>
  <%= @artwork.description %>
</p>

<p>
  <strong>Medium:</strong>
  <%= @artwork.medium %>
</p>

<p>
  <strong>Dimensions:</strong>
  <%= @artwork.dimensions %>
</p>

<%= link_to 'Edit', edit_artwork_path(@artwork) %> |
<%= link_to 'Back', artworks_path %>

app/views/exhibitions/_form.html.erb
<%= form_for(@exhibition) do |f| %>
  <% if @exhibition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exhibition.errors.count, "error") %> prohibited this exhibition from being saved:</h2>

      <ul>
      <% @exhibition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :site %><br>
    <%= f.text_field :site %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :opening %><br>
    <%= f.date_select :opening %>
  </div>
  <div class="field">
    <%= f.label :closing %><br>
    <%= f.date_select :closing %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exhibitions/edit.html.erb
<h1>Editing exhibition</h1>

<%= render 'form' %>

<%= link_to 'Show', @exhibition %> |
<%= link_to 'Back', exhibitions_path %>

app/views/exhibitions/index.html.erb
<h1>Listing exhibitions</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Title</th>
      <th>Site</th>
      <th>City</th>
      <th>Opening</th>
      <th>Closing</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exhibitions.each do |exhibition| %>
      <tr>
        <td><%= exhibition.title %></td>
        <td><%= exhibition.site %></td>
        <td><%= exhibition.city %></td>
        <td><%= exhibition.opening %></td>
        <td><%= exhibition.closing %></td>
        <td><%= exhibition.comment %></td>
        <td><%= link_to 'Show', exhibition %></td>
        <td><%= link_to 'Edit', edit_exhibition_path(exhibition) %></td>
        <td><%= link_to 'Destroy', exhibition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exhibition', new_exhibition_path %>

app/views/exhibitions/new.html.erb
<h1>New exhibition</h1>

<%= render 'form' %>

<%= link_to 'Back', exhibitions_path %>

app/views/exhibitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @exhibition.title %>
</p>

<p>
  <strong>Site:</strong>
  <%= @exhibition.site %>
</p>

<p>
  <strong>City:</strong>
  <%= @exhibition.city %>
</p>

<p>
  <strong>Opening:</strong>
  <%= @exhibition.opening %>
</p>

<p>
  <strong>Closing:</strong>
  <%= @exhibition.closing %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @exhibition.comment %>
</p>

<%= link_to 'Edit', edit_exhibition_path(@exhibition) %> |
<%= link_to 'Back', exhibitions_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '', root_path, class: 'navbar-brand glyphicon glyphicon-home' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Artworks', artworks_path %></li>
<li><%= link_to 'Exhibitions', exhibitions_path %></li>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Artwareclients20" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Artwareclients20" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

app/views/visitors/new.html.erb
<h3>Home</h3>